# Makefile : build executable Windows
w-exe: main.c
		x86_64-w64-mingw32-gcc -o sarah.exe	main.c parsing.c parsing_utils.c parsing_utils2.c moves.c moves2.c init.c free.c exit.c Libft/libft.a mlx/libmlx.a
